layout_spectrum: 0.35380571824498475
typography_spectrum: 0.23037914792075753
color:
  brandStrength: 0.7982033465523273
  lightness: 0.6547181576024741
  saturation: 0.6203869902528822
  rhythmicContrast: 0.5699853044934571
  brandColors:
    - '#E1E6FA'
    - '#C4D7ED'
    - '#ABC8E2'
    - '#375D81'
    - '#183152'
name: hooton.org
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/0b127d12-a9b0-4245-9fc0-d4a02995258c.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/0b127d12-a9b0-4245-9fc0-d4a02995258c.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      inLanguage: !<tag:yaml.org,2002:js/undefined> ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
github: true
title: DAVID HOOTON
description: 'Nerd wrangler, Telco entrepreneur, lover of bacon..'
